version: '3'
services:
  backend:
    image: serverimg
    ports:
      - '8080:8080'
    networks:
      - my_network

  mymongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
